// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface OfferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Offer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double stockPrice = 2;</code>
   * @return The stockPrice.
   */
  double getStockPrice();

  /**
   * <code>int32 numberOfOffers = 3;</code>
   * @return The numberOfOffers.
   */
  int getNumberOfOffers();

  /**
   * <code>bool buy = 4;</code>
   * @return The buy.
   */
  boolean getBuy();

  /**
   * <code>string clientId = 5;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 5;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
