// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public final class StocksServiceOuterClass {
  private StocksServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Stock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Stock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeUpit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeUpit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyOffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuyOffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SellOffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SellOffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024stocks_service.proto\"i\n\005Stock\022\016\n\006symbo" +
      "l\030\001 \001(\t\022\023\n\013companyName\030\002 \001(\t\022\022\n\nstartPri" +
      "ce\030\003 \001(\001\022\025\n\rchangeInPrice\030\004 \001(\001\022\020\n\010dateU" +
      "nix\030\005 \001(\003\" \n\rSubscribeUpit\022\017\n\007symbols\030\001 " +
      "\003(\t\"\036\n\014StockRequest\022\016\n\006symbol\030\001 \001(\t\"4\n\nB" +
      "idRequest\022\016\n\006symbol\030\001 \001(\t\022\026\n\016numberOfOff" +
      "ers\030\002 \001(\005\"4\n\nAskRequest\022\016\n\006symbol\030\001 \001(\t\022" +
      "\026\n\016numberOfOffers\030\002 \001(\005\"F\n\010BuyOffer\022\016\n\006s" +
      "ymbol\030\001 \001(\t\022\022\n\nstockPrice\030\002 \001(\001\022\026\n\016numbe" +
      "rOfOffers\030\003 \001(\005\"G\n\tSellOffer\022\016\n\006symbol\030\001" +
      " \001(\t\022\022\n\nstockPrice\030\002 \001(\001\022\026\n\016numberOfOffe" +
      "rs\030\003 \001(\005\"\007\n\005Empty2\253\002\n\rStocksService\022#\n\010G" +
      "etStock\022\r.StockRequest\032\006.Stock\"\000\022\"\n\014GetA" +
      "llStocks\022\006.Empty\032\006.Stock\"\0000\001\022-\n\017Subscrib" +
      "eStocks\022\016.SubscribeUpit\032\006.Stock\"\0000\001\022*\n\014G" +
      "etBuyOffers\022\013.BidRequest\032\t.BuyOffer\"\0000\001\022" +
      ",\n\rGetSellOffers\022\013.AskRequest\032\n.SellOffe" +
      "r\"\0000\001\022\"\n\013AddBuyOffer\022\t.BuyOffer\032\006.Empty\"" +
      "\000\022$\n\014AddSellOffer\022\n.SellOffer\032\006.Empty\"\000B" +
      "\031\n\025rs.raf.pds.v5.z2.gRPCP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Stock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Stock_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "StartPrice", "ChangeInPrice", "DateUnix", });
    internal_static_SubscribeUpit_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SubscribeUpit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeUpit_descriptor,
        new java.lang.String[] { "Symbols", });
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "Symbol", });
    internal_static_BidRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_descriptor,
        new java.lang.String[] { "Symbol", "NumberOfOffers", });
    internal_static_AskRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskRequest_descriptor,
        new java.lang.String[] { "Symbol", "NumberOfOffers", });
    internal_static_BuyOffer_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BuyOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuyOffer_descriptor,
        new java.lang.String[] { "Symbol", "StockPrice", "NumberOfOffers", });
    internal_static_SellOffer_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SellOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SellOffer_descriptor,
        new java.lang.String[] { "Symbol", "StockPrice", "NumberOfOffers", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
