// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface StockArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Stock stocks = 1;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.Stock> 
      getStocksList();
  /**
   * <code>repeated .Stock stocks = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.Stock getStocks(int index);
  /**
   * <code>repeated .Stock stocks = 1;</code>
   */
  int getStocksCount();
  /**
   * <code>repeated .Stock stocks = 1;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.StockOrBuilder> 
      getStocksOrBuilderList();
  /**
   * <code>repeated .Stock stocks = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.StockOrBuilder getStocksOrBuilder(
      int index);
}
