// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public final class StocksServiceOuterClass {
  private StocksServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Stock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Stock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeUpit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeUpit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockUpit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockUpit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024stocks_service.proto\"i\n\005Stock\022\016\n\006symbo" +
      "l\030\001 \001(\t\022\023\n\013companyName\030\002 \001(\t\022\022\n\nstartPri" +
      "ce\030\003 \001(\001\022\025\n\rchangeInPrice\030\004 \001(\001\022\020\n\010dateU" +
      "nix\030\005 \001(\003\" \n\rSubscribeUpit\022\017\n\007symbols\030\001 " +
      "\003(\t\"\033\n\tStockUpit\022\016\n\006symbol\030\001 \001(\t\"\007\n\005Empt" +
      "y2\204\001\n\rStocksService\022 \n\010GetStock\022\n.StockU" +
      "pit\032\006.Stock\"\000\022-\n\017SubscribeStocks\022\016.Subsc" +
      "ribeUpit\032\006.Stock\"\0000\001\022\"\n\014GetAllStocks\022\006.E" +
      "mpty\032\006.Stock\"\0000\001B\031\n\025rs.raf.pds.v5.z2.gRP" +
      "CP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Stock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Stock_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "StartPrice", "ChangeInPrice", "DateUnix", });
    internal_static_SubscribeUpit_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SubscribeUpit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeUpit_descriptor,
        new java.lang.String[] { "Symbols", });
    internal_static_StockUpit_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockUpit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockUpit_descriptor,
        new java.lang.String[] { "Symbol", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
