// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface StockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Stock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string companyName = 2;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 2;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>double startPrice = 3;</code>
   * @return The startPrice.
   */
  double getStartPrice();

  /**
   * <code>double changeInPrice = 4;</code>
   * @return The changeInPrice.
   */
  double getChangeInPrice();

  /**
   * <code>int64 dateUnix = 5;</code>
   * @return The dateUnix.
   */
  long getDateUnix();
}
