// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code Stock}
 */
public final class Stock extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Stock)
    StockOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Stock.newBuilder() to construct.
  private Stock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Stock() {
    symbol_ = "";
    companyName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Stock();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StocksServiceOuterClass.internal_static_Stock_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StocksServiceOuterClass.internal_static_Stock_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.Stock.class, rs.raf.pds.v5.z2.gRPC.Stock.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANYNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object companyName_ = "";
  /**
   * <code>string companyName = 2;</code>
   * @return The companyName.
   */
  @java.lang.Override
  public java.lang.String getCompanyName() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyName_ = s;
      return s;
    }
  }
  /**
   * <code>string companyName = 2;</code>
   * @return The bytes for companyName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyNameBytes() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTPRICE_FIELD_NUMBER = 3;
  private double startPrice_ = 0D;
  /**
   * <code>double startPrice = 3;</code>
   * @return The startPrice.
   */
  @java.lang.Override
  public double getStartPrice() {
    return startPrice_;
  }

  public static final int CHANGEINPRICE_FIELD_NUMBER = 4;
  private double changeInPrice_ = 0D;
  /**
   * <code>double changeInPrice = 4;</code>
   * @return The changeInPrice.
   */
  @java.lang.Override
  public double getChangeInPrice() {
    return changeInPrice_;
  }

  public static final int DATEUNIX_FIELD_NUMBER = 5;
  private long dateUnix_ = 0L;
  /**
   * <code>int64 dateUnix = 5;</code>
   * @return The dateUnix.
   */
  @java.lang.Override
  public long getDateUnix() {
    return dateUnix_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(companyName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, companyName_);
    }
    if (java.lang.Double.doubleToRawLongBits(startPrice_) != 0) {
      output.writeDouble(3, startPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(changeInPrice_) != 0) {
      output.writeDouble(4, changeInPrice_);
    }
    if (dateUnix_ != 0L) {
      output.writeInt64(5, dateUnix_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(companyName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, companyName_);
    }
    if (java.lang.Double.doubleToRawLongBits(startPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, startPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(changeInPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, changeInPrice_);
    }
    if (dateUnix_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, dateUnix_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.Stock)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.Stock other = (rs.raf.pds.v5.z2.gRPC.Stock) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getCompanyName()
        .equals(other.getCompanyName())) return false;
    if (java.lang.Double.doubleToLongBits(getStartPrice())
        != java.lang.Double.doubleToLongBits(
            other.getStartPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getChangeInPrice())
        != java.lang.Double.doubleToLongBits(
            other.getChangeInPrice())) return false;
    if (getDateUnix()
        != other.getDateUnix()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + COMPANYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyName().hashCode();
    hash = (37 * hash) + STARTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getStartPrice()));
    hash = (37 * hash) + CHANGEINPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getChangeInPrice()));
    hash = (37 * hash) + DATEUNIX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDateUnix());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.Stock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.Stock prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Stock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Stock)
      rs.raf.pds.v5.z2.gRPC.StockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StocksServiceOuterClass.internal_static_Stock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StocksServiceOuterClass.internal_static_Stock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.Stock.class, rs.raf.pds.v5.z2.gRPC.Stock.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.Stock.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      companyName_ = "";
      startPrice_ = 0D;
      changeInPrice_ = 0D;
      dateUnix_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StocksServiceOuterClass.internal_static_Stock_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.Stock getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.Stock.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.Stock build() {
      rs.raf.pds.v5.z2.gRPC.Stock result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.Stock buildPartial() {
      rs.raf.pds.v5.z2.gRPC.Stock result = new rs.raf.pds.v5.z2.gRPC.Stock(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.Stock result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.companyName_ = companyName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.startPrice_ = startPrice_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.changeInPrice_ = changeInPrice_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dateUnix_ = dateUnix_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.Stock) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.Stock)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.Stock other) {
      if (other == rs.raf.pds.v5.z2.gRPC.Stock.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCompanyName().isEmpty()) {
        companyName_ = other.companyName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getStartPrice() != 0D) {
        setStartPrice(other.getStartPrice());
      }
      if (other.getChangeInPrice() != 0D) {
        setChangeInPrice(other.getChangeInPrice());
      }
      if (other.getDateUnix() != 0L) {
        setDateUnix(other.getDateUnix());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              companyName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              startPrice_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              changeInPrice_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 40: {
              dateUnix_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object companyName_ = "";
    /**
     * <code>string companyName = 2;</code>
     * @return The companyName.
     */
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string companyName = 2;</code>
     * @return The bytes for companyName.
     */
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string companyName = 2;</code>
     * @param value The companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      companyName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string companyName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyName() {
      companyName_ = getDefaultInstance().getCompanyName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string companyName = 2;</code>
     * @param value The bytes for companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      companyName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double startPrice_ ;
    /**
     * <code>double startPrice = 3;</code>
     * @return The startPrice.
     */
    @java.lang.Override
    public double getStartPrice() {
      return startPrice_;
    }
    /**
     * <code>double startPrice = 3;</code>
     * @param value The startPrice to set.
     * @return This builder for chaining.
     */
    public Builder setStartPrice(double value) {

      startPrice_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double startPrice = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      startPrice_ = 0D;
      onChanged();
      return this;
    }

    private double changeInPrice_ ;
    /**
     * <code>double changeInPrice = 4;</code>
     * @return The changeInPrice.
     */
    @java.lang.Override
    public double getChangeInPrice() {
      return changeInPrice_;
    }
    /**
     * <code>double changeInPrice = 4;</code>
     * @param value The changeInPrice to set.
     * @return This builder for chaining.
     */
    public Builder setChangeInPrice(double value) {

      changeInPrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double changeInPrice = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearChangeInPrice() {
      bitField0_ = (bitField0_ & ~0x00000008);
      changeInPrice_ = 0D;
      onChanged();
      return this;
    }

    private long dateUnix_ ;
    /**
     * <code>int64 dateUnix = 5;</code>
     * @return The dateUnix.
     */
    @java.lang.Override
    public long getDateUnix() {
      return dateUnix_;
    }
    /**
     * <code>int64 dateUnix = 5;</code>
     * @param value The dateUnix to set.
     * @return This builder for chaining.
     */
    public Builder setDateUnix(long value) {

      dateUnix_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 dateUnix = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateUnix() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dateUnix_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Stock)
  }

  // @@protoc_insertion_point(class_scope:Stock)
  private static final rs.raf.pds.v5.z2.gRPC.Stock DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.Stock();
  }

  public static rs.raf.pds.v5.z2.gRPC.Stock getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Stock>
      PARSER = new com.google.protobuf.AbstractParser<Stock>() {
    @java.lang.Override
    public Stock parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Stock> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Stock> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.Stock getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

