// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface SubscribeUpitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscribeUpit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string symbols = 1;</code>
   * @return A list containing the symbols.
   */
  java.util.List<java.lang.String>
      getSymbolsList();
  /**
   * <code>repeated string symbols = 1;</code>
   * @return The count of symbols.
   */
  int getSymbolsCount();
  /**
   * <code>repeated string symbols = 1;</code>
   * @param index The index of the element to return.
   * @return The symbols at the given index.
   */
  java.lang.String getSymbols(int index);
  /**
   * <code>repeated string symbols = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the symbols at the given index.
   */
  com.google.protobuf.ByteString
      getSymbolsBytes(int index);

  /**
   * <code>string clientId = 2;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 2;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
