// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface TransactionHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransactionHistory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientIdSeller = 1;</code>
   * @return The clientIdSeller.
   */
  java.lang.String getClientIdSeller();
  /**
   * <code>string clientIdSeller = 1;</code>
   * @return The bytes for clientIdSeller.
   */
  com.google.protobuf.ByteString
      getClientIdSellerBytes();

  /**
   * <code>string clientIdBuyer = 2;</code>
   * @return The clientIdBuyer.
   */
  java.lang.String getClientIdBuyer();
  /**
   * <code>string clientIdBuyer = 2;</code>
   * @return The bytes for clientIdBuyer.
   */
  com.google.protobuf.ByteString
      getClientIdBuyerBytes();

  /**
   * <code>string symbol = 3;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 3;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double price = 4;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 numberOfShares = 5;</code>
   * @return The numberOfShares.
   */
  int getNumberOfShares();

  /**
   * <code>int64 dateUnix = 6;</code>
   * @return The dateUnix.
   */
  long getDateUnix();
}
