// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface TransactionHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransactionHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   * @return The day.
   */
  int getDay();

  /**
   * <code>string symbol = 4;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 4;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();
}
